### PR TITLE
test: fix incorrect test

### PR DESCRIPTION
**Pull request by jquense**
### Notable Changes

fixes a test that is incorrectly rewritten

### Type

> ℹ️ What type of changes does your code introduce?

- [ ] CI
- [ ] Fix
- [ ] Perf
- [ ] Docs
- [x] Test
- [ ] Style
- [ ] Build
- [ ] Chore
- [ ] Feature
- [ ] Refactor

### Checklist

> ℹ️  You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. This is a reminder of what we are going to look for before merging your code.

- [x] Lint and unit tests pass with my changes
- [x] I have added tests that prove my fix is effective/works (if needed)
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes are merged and published in downstream modules

### CODE REVIEW

**Comment by jquense** [comment]
ping

**Comment by evilebottnawi** [comment]
hm CI failed :disappointed:

**Comment by jquense** [comment]
yes it's just broken generally, for any PR. The problem is node 12 is producing slightly different snapshot results, than node 10 was and CI is configured to run on "latest". see: https://github.com/webpack-contrib/postcss-loader/pull/425#discussion_r419386324

**Comment by evilebottnawi** [comment]
Oh, yes, we need to setup github actions, in my TODO on this week, I will ping you

**Pull request closed without merging**
